#
# mozaik generic demo dashboard
#
# It's not required, but you should add this env var,
# without it, you'll probably reach the API rate limit.
#
# GITHUB_API_TOKEN=xxxxx
#
port: 5000

# define duraton between each dashboard rotation (ms)
rotationDuration: 10000
# define the interval used by Mozaïk Bus to call registered APIs
apisPollInterval: 100000

dashboards:
- columns: 4
  rows:    4
  title:   Mozaïk PS Demo Dashboard
  widgets:
  -
    extension:   table
    widget:      Table
    title:       Team
    fields:
      -
        Name:   '{name}'
      -
        Level:  '{designation}'
    url:        http://localhost:8081/rest/employees
    columns:     2
    rows:        2
    x:           0
    y:           0
  -
    extension:   table
    widget:      Table
    title:       Departments
    fields:
      -
        Name:   '{name}'
      -
        Desc:  '{description}'
    url:        http://localhost:8081/rest/departments
    columns:     2
    rows:        2
    x:           2
    y:           0
